askcompany/urls.py
from django.contrib import admin
from django.urls import path, include

#from django.conf import global_settings
#from askcompany.urls import settings     이렇게 사용하면 안된다
from django.conf import settings # 위에 두개를 한번에 사용가능

from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    #path('',TemplateView.as_view(template_name='root.html'), name='root'),
    path('',RedirectView.as_view(
        #url = "/instagram/"
        pattern_name = "instagram:post_list", #url_reverse app_name과 path 인자 name 지정되있을떄 사용가능
        ), name='root'),

    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls')),
    path('pratice/', include('practice.urls')),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG: #DEBUG가 참일떄만 개발모드일때만 True임
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    #하는 이유 settings.py에 MEDIA_URL 설정해 두었지만 urls에서 페이지설정 따로하지않아 urlpatterns에 추가해야 해당 파일 url 사용가능

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

#askcompany setting을 가지고왔다.
#settings.MEDIA_URL
#settings.MEDIA_ROOT

blog1/urls.py
from . import views
from django.urls import path

app_name = "blog1"  #안넣어도 구동가능, URL_REVERSE에서 namespace 역할을 하게된다.

urlpatterns = [
    path('', views.PostList, name='post_list'),
]

instagram/urls.py
from django.urls import path, re_path, register_converter
from . import views
from .converters import YearConverter, MonthConverter, DayConverter



register_converter(YearConverter, 'year')## custom converter 만듬, 자주쓰는 url 패턴의경우 만든다.
register_converter(MonthConverter, 'month')
register_converter(DayConverter, 'day')

app_name = "instagram" #안넣어도 구동가능, URL_REVERSE에서 namespace 역할을 하게된다.

urlpatterns=[
    path('new/', views.post_new, name='post_new' ),
    path('', views.post_list, name = 'post_list'),
    path('<int:pk>/',views.post_detail, name='post_detail'),#re_path(r'(?P<pk>\d+)/$', views.post_detail), #위와 같은의미
    path('<int:pk>/edit/',views.post_edit, name='post_edit'),
    path('<int:pk>/delete/',views.post_delete, name='post_delete'), #삭제

    # path('archives/<year:year>/', views.archives_year),
    #path('archives/<int:year>/', views.archives_year),
    #re_path(r'archives/(?P<year>\d+)/', views.archives_year), #정규포현식을 사용 원하는 정확한 인자로 주소설정가능 (?P<year>\d+)
    path('archive/', views.post_archive, name='post_archive'),
    path('archive/<year:year>/', views.post_archive_year, name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/', views.post_archive_month, name='post_archive_month'),
    # path('archive/<year:year>/<month:month>/<day:day>/', views.post_archive_day, name='post_archive_day'),

]

instagram/models.py
from distutils.command.upload import upload
#from email import message
from django.db import models
#from django.contrib.auth.models import User #굉장히 딱딱한 방식
from django.conf import settings #user import의 다른 방식
from django.urls import reverse
from django.core.validators import MinLengthValidator #모델폼에서 사용하는 검증방법


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(
        validators=[MinLengthValidator(3)] #3글자 이상만
    )
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y%m%d') #upload setting에 설정된 media 안에 저장폴더 상세설정(너무많은 media 파일들을 관리하기위하여)
                                                                             # 이때 저장장소를 함수로 설정할경우(문자열로 반환) 파일명을 원하는 것으로 변경 가능
    tag_set = models.ManyToManyField('Tag', blank=True) #다대 다인경우 blank가 필요할수 있다.
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    # 자바 toString

    def __str__(self): # admin에서 class -> list_display 설정하여 보이지 않는다
        #return f"Custom Post objects ({self.id}) " 
        return f"{self.pk} : {self.message}"

    def get_absolute_url(self): # url-reverse위한 필수
        return reverse('instagram:post_detail', args=[self.pk])

    class Meta: # 기본정렬 default 정렬
        ordering = ['-id']

    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = "메시지 글자수" ## admin에서 display_list 할경우 colunm 이름 변경


class Comment(models.Model):  # 1 : N ForeingKey의 경우 N에 명시하면 된다.
    post = models.ForeignKey(Post, on_delete=models.CASCADE ## 실제로는 post_id 필드가 db에 생성된다
                            ,limit_choices_to={'is_public':True}) # is_public :True인것만 연결하겠다.
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    #post_set = models.ManyToManyField(Post)

    def __str__(self) :
        return self.name

instagram/forms.py
from django import forms
from .models import Post
import re

#모델폼과 일반폼 차이점
#일반 폼은 폼 자체에서 데이터 받는 검증 형식 지정해야한다.
#모델 폼은 모델에 정의되어있는 검증 맞게 데이터 받는다.

class PostForm(forms.ModelForm): 
    class Meta:
        model = Post
        # fields = '__all__'
        fields = [
            'message', 'photo', 'tag_set', 'is_public'
        ] #이것만하면 문제점 여기서는 작성자를 지정하지않아서

    def clean_message(self):# 유효성검사시 자동으로 실행된다. / clean_필드명으로 필드에 유효성검사
        message = self.cleaned_data.get('message')
        # if message:
        #     message = re.sub('[a-zA-z]', '', message)
        
        return message

instagram/views.py
from django.urls import reverse, reverse_lazy
from http.client import HTTPResponse
from urllib import response
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import redirect, render,get_object_or_404
from .models import Post
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required # 장식자 호출
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostForm

# post_list = login_required(ListView.as_view(model = Post, paginate_by = 10)) #클래스 기반 뷰 아직 검색기능 미구현

# 새로운 포스트 생성
# @login_required
# def post_new(request): ##form 사용법
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             # post = form.save(commit=True)#commit default : true / 인스턴스를 save 할것이냐 false일시 데이터 저장 안됨 / post.save가 생략될수 있다.
#             # post = form.save(commit=False)
#             # post.save()
#             post = form.save(commit=False)# form에는 user가 생략되어있어서 사용
#             post.author = request.user #현재 로그인 유저확인
#             post.save() # user 받고 저장
            
#             #message # 소비하는 코드는 layout.html
#             messages.success(request, '포스팅을 저장하였습니다.')

#             return redirect(post)
#     else:
#         form = PostForm()

#     return render(request, 'instagram/post_form.html', {
#         'form':form,
#         'post': None,        
#     })

class PostCreateView(LoginRequiredMixin ,CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request, '포스팅을 저장하였습니다.')
        return super().form_valid(form)

post_new = PostCreateView.as_view()

#Post 수정
# @login_required #로그인 필요 장식자
# def post_edit(request, pk):
#     post = get_object_or_404(Post,pk=pk)

#     # 작성자 check tip
#     if post.author != request.user:
#         messages.error(request, '작성자만 수정가능합니다.')
#         return redirect(post)
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save() # 수정의경우 user가 이미 지정되어있어 commit default

#             #message # 소비하는 코드는 layout.html
#             messages.success(request, '포스팅을 수정하였습니다.')

#             return redirect(post)
#     else:
#         form = PostForm(instance=post)

#     return render(request, 'instagram/post_form.html', {
#         'form':form,
#         'post': post,
#     })

class PostUpdateView(LoginRequiredMixin ,UpdateView): #아직 작성자만 고치는거는 미구현?
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.success(self.request, '포스팅을 수정하였습니다.')
        return super().form_valid(form)

post_edit = PostUpdateView.as_view()



# 포스트 삭제
# @login_required 
# def post_delete(request, pk):
#     post = get_object_or_404(Post,pk=pk)
#     if request.method== 'POST':
#         post.delete()
#         messages.success(request, "포스팅을 삭제하였습니다.")
#         return redirect('instagram:post_list')

#     return render(request, 'instagram/post_confirm_delete.html',{
#         'post':post
#     })

class PostDeleteView(LoginRequiredMixin ,DeleteView): #아직 작성자만 고치는거는 미구현?
    model = Post
    # success_url = reverse('instagram:post_list') #안된다 호출이 먼저되서 안된다

    success_url = reverse_lazy('instagram:post_list') #이 값이 사용될떄 호출 된다. 호출 해결방법 2
    # def get_success_url(self):  # 호출 해결방법 1
    #     return reverse('instagram:post_list')

post_delete = PostDeleteView.as_view()




#@method_decorator(login_required, name = 'dispatch')
class PostListView(ListView): # 장식자 로그인 접근방법과 상속을 통한 로그인 접속방법
    model = Post
    paginate_by = 100

post_list = PostListView.as_view(paginate_by=20)



# @login_required #로그인 여부, 안되어 있을시 로그인 페이지로 / 주소 defalut : accounts/login
# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q', '') #url에서 post_list 함수를 호출시 해당 url에서 GET 해라 'q'라는 인자를 반환 # 'q' 가 없을시 '' 반환 (검색어저장)

#     if q:
#         qs = qs.filter(message__icontains= q)

    

#     #instagram/templates/instagram/post_list.html
#     return render(request, 'instagram/post_list.html', {
#         'post_list' : qs,
#         'q':q,

#     })

#아래 : --> type형태에 대한 hint의 라고 보면된다. 타입틀려도 eror x

# def post_detail(request:HttpRequest, pk : int):# -> HttpResponse:
#     # try:
#     #     post = Post.objects.get(pk=pk) #url에서 받은 pk값과 일치하는 Post 가지고와라 # pk 없을시 DoesNotExits 에러발생한다.
#     # except Post.DoesNotExist:
#     #     raise Http404
#     post = get_object_or_404(Post, pk=pk) #위 try except를 간소화할수 있다.
  
#     return render(request, "instagram/post_detail.html",{
#         'post':post,
#     })
#     #response = HttpResponse()
#     #response.write("Hello world")
#     #return response
post_detail = DetailView.as_view(model=Post)

# def archives_year(request, year):
#     return HttpResponse(f"{year} archives")

post_archive = ArchiveIndexView.as_view(model=Post, date_field = 'created_at', paginate_by =10)

post_archive_year = YearArchiveView.as_view(model=Post, date_field = 'created_at', make_object_list = True)

instagram/templates/instagram/post_archive.html
<h2>latest</h2>

{{latest}}

<h2>date_list</h2>

{% for date in date_list %}
    {{date|date:"Y"}}
    {{date.year}}
{% endfor %}

instagram/templates/instagram/post_archive_year.html
<h2>year</h2>
{{year}}


<h2>previous_year</h2>
{{previous_year}}


<h2>next_year</h2>
{{next_year}}


<h2>date_list</h2>
{{date_list}}

<h2>object_list</h2>
{{object_list}}

instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}

        <div class='alert alert-danger'>
            정말 삭제하시겠습니까?
        </div>

        <a href="{{post.get_absolute_url}}" class='btn btn-secondary'>
            취소
        </a>

        <input type='submit' value="삭제하겠습니다" class='btn btn-danger'>
    </form>

{% endblock content %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %} <!--상속받는다.-->
{% load bootstrap4 %}

{% block title %}
    Post Deatail
{% endblock title %}

{% block content %}
    <h2>Author : {{post.author}}</h2>


    {% if post.photo %}
        <div>
        <img src="{{post.photo.url}}" style="height: 100px;">
    </div>
    {% endif %}
    {{post.message | linebreaks}}
    <hr/>
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">목록</a>
    <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">수정</a>
    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">삭제</a>
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}


{% block content %}
    <form action='' method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form form %}

        {% buttons %}
            <button class='btn btn-primary'>
                저장
            </button>

        {% endbuttons%}


        <!-- <table>
            {{form}}
        </table>
        <input type="submit" value="저장"> -->

    </form>
    <hr/>
    {%if post %} <!-- form이 Post 수정인경우 -->
        <a href = '{{form.instance.get_absolute_url}}' class = "btn btn-secondary"> 내용으로</a>
    {% endif  %}
        <a href = "{% url 'instagram:post_list' %}" class = "btn btn-primary">목록</a>

{% endblock %}

instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %} <!--상속받는다.-->
{% load bootstrap4 %}


{% block title %}
    Instagram/post_list
{% endblock title %}

{% block content %}
    <!-- <script>
    if(1>0){
        console.log('script console test');
        alert("script console test");
    }
    </script> -->
    <form action="" method="get"> <!--action이 비어있으므로 상대경로로 웹페이지 생성?-->
        <input type = 'text' name='q' value="{{q}}">
        <input type = 'submit' value="검색">
    </form>
    
    <a href='{% url 'instagram:post_new' %}' class='btn btn-primary btn-block mt-3 mb-3'>
        새포스트
    </a>
    <table class="table table-bordered table-hover"> <!--이 table은 bootstrap 가지고와서 쓸수있는거(디자인)-->
        <tbody>
            {% for post in post_list %}
            <tr>
                <td>
                    {{post.pk}}
                </td>

                <td>
                    {% if post.photo %}
                        <img src="{{post.photo.url}}" style="width: 100px;">
                    {% else %}
                        no photo
                    {% endif %}
                </td>
                <td>
                    <!--<a href="/instagram/{{post.pk}}/">이 방식은 instagram 자체 url 변경시 사용불가해진다. url-reverse 사용하는 이유 -->
                        <!-- <a href={% url "instagram:post_detail" post.pk%} > url reverse 방식 -->
                            <!--모델에 get_absolute_url 지정시-->
                            <a href="{{post.get_absolute_url}}" >
                        {{post.message}}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    {% if is_paginated %}
    {% bootstrap_pagination page_obj size="large" justify_content="center"%}    
    {% endif %}
    {{page_obj}}
{% endblock content %}